
spring:
  application:
    name: turbine
  rabbitmq:
      host: 192.168.100.3
      port: 5673
      username: admin
      password: admin
server:
  port: 8989
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
turbine:
  app-config: consumer-feign
  cluster-name-expression: "'default'"
#  combine-host-port: true