
spring:
  application:
    name: turbine
server:
  port: 8989
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
turbine:
  app-config: consumer-feign
  cluster-name-expression: "'default'"
#  combine-host-port: true