server:
  port: 8010
spring:
  application:
    name: consumer-movie-feign-ribbon-customing
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level: debug
feign:
  hystrix:
    enabled: true