server:
  port: 8010
spring:
  application:
    name: consumer-feign
  rabbitmq:
    host: 192.168.100.3
    port: 5673
    username: admin
    password: admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level: debug
feign:
  hystrix:
    enabled: true